### ISSUE TITLE
Lua default libs not loaded in Lua5.2

### ISSUE THREAD

**Issue by pmusa** [askyrme/luaproc#6]
In Lua5.2 when using string, io, etc. inside a worker it raises:
close lua_State (error: exec.lua:17: attempt to index global 'io' (a nil value))

**Comment by imuzi** [comment]
Still needs require again in new process before using them!

**Comment by askyrme** [comment]
This is not actually an issue - it works like this by design (and has been working like this since earlier luaproc versions). Only essential libraries (base and package) are loaded, all others must be explicitly required in new Lua processes, as proposed in Programming in Lua (PiL). Check PiL (3rd ed), chapter 31 (Threads and States), page 331: "Whenever a process needs one of these libraries, it requires the library explicitly, and require will call the corresponding luaopen_* function".
